### ISSUE TITLE
Missing demo.mp4 video for testing

### ISSUE THREAD

**Issue by laurelrr** [Tyelab/AlphaTracker2#5]
It looks like the demo.mp4 video that matches the demo training data is no longer included in the alphatracker 1.0 repo.

**Comment by ZY-UA** [comment]
When run the code: at2.train_pose_estimator(expname, epochs=50, nThreads=0) (at the fifth step), it stopped because of the ValueError.
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by laurelrr** [comment]
sample clip of 2 mice:
https://drive.google.com/file/d/1N0JjazqW6JmBheLrn6RoDTSRXSPp1t4K


Sample annotated data (600 images of 2 mice, 4 body parts each) :
https://drive.google.com/file/d/15dR-vVCEsg2z7mEVzJOF9YDW6YioEU3N'
