### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by ZY-UA** [Tyelab/AlphaTracker2#8]
Hi, 
When run the code: at2.train_pose_estimator(expname, epochs=50, nThreads=0) (at the fifth step), it stopped because of the ValueError.
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by laurelrr** [comment]
Hi,
My apologies for the delayed response to your issue.  I need some more information to assist you.  Could you verify that the training data correctly downloaded to your folder?  There should be about 600 images of size 245KB.  Are your images only 2KB?

**Comment by laurelrr** [comment]
I have not heard back from you on this issue, so I am going to close it out.  If the problem persists, please open a new issue.  Thanks!
